const en = {
  'buttons.create': "Create",
  'buttons.apply': "Apply",
  'button.cancel': "Cancel",

  'explorer.tabs.flows': 'flows',
  'explorer.tabs.services': 'services',
  'explorer.tabs.decisions': 'decisions',
  'explorer.tabs.search': 'search',

  'activities.title': 'Activities',
  'activities.desc': 'Create, view, and navigate site resources',

  'activities.flows.title': 'Flows',
  'activities.flows.desc': 'TODO:: ',

  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'TODO:: ',

  'activities.services.title': 'Services',
  'activities.services.desc': 'TODO:: ',

  'activities.migration.title': 'Migration',
  'activities.migration.desc': 'TODO:: ',

  'activities.types.title': 'Types',
  'activities.types.desc': 'TODO:: ',
  'activities.types.view': 'View all types',

  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.releases.view': 'View all releases',
  'activities.releases.graph': 'Graph',

  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'FEATURE IS NOT IMPLEMENTED YET, BUT IT IS COMING SOON!  Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. ',
  'activities.templates.view': 'View all templates',

  'programs.error.title': 'Program error',
  'programs.warning.title': 'Program warning',



  'flows': "Flows",
  'options': "Options",

  'flows.edit.title': "Edit flow",
  'flows.copyas.title': "Copy flow as",
  'flows.delete.title': "Delete flow",
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task': "Add existing asset or create new one",
  'flows.autocomplete.task.snackbar.created': "Created new {type}: {name}",
  'flows.autocomplete.task.snackbar.creating': "Creating new {type}: {name}",

  'services.edit.title': "Edit service",
  'services.copyas.title': "Copy service as",
  'services.delete.title': "Delete service",

  'decisions.name': "Name",
  'decisions.desc': "Description",
  'decisions.hitpolicy': "Hit-policy",
  'decisions.edit.title': "Edit decision",
  'decisions.copyas.title': "Copy decision as",
  'decisions.delete.title': "Delete decision",
  'decisions.table.hitpolicy': "Matches",
  'decisions.table.options': "Options",

  'decisions.toolbar.addInputColumn': "Add input column",
  'decisions.toolbar.addOutputColumn': "Add output column",
  'decisions.toolbar.addRow': "Add row",
  'decisions.toolbar.csvDownload': "Download CSV, with separator ';'",
  'decisions.toolbar.csvUpload': "Upload CSV, with separator ';'",
  'decisions.toolbar.nameAndHitpolicy': "Name and hit-policy",
  'decisions.toolbar.organize.rows.columns': "Organize rows and columns",
  'decisions.toolbar.organize.action': "Select action",
  'decisions.toolbar.organize.action.helper': "Move column or row based on name/index",
  'decisions.toolbar.organize.action.expression': "Select expression",
  'decisions.toolbar.organize.action.expression.column': "Select column",
  'decisions.toolbar.organize.action.deleteColumn': "Delete whole column",
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': "Column to move",
  'decisions.toolbar.organize.action.move.from.row': "Row to move",
  'decisions.toolbar.organize.action.move.to.column': "New Position",
  'decisions.toolbar.organize.action.move.to.row': "New Position",

  'decisions.table.inputs.title': "Matching rules",
  'decisions.table.outputs.title': "Results",
  'decisions.cells.dialog.title': "Decision table: {name}, column: {column}, value: {value}",
  'decisions.cells.newvalue.boolean': "Enter new value",
  'decisions.cells.newvalue.boolean.helper': "Select boolean value",
  'decisions.cells.newvalue.boolean.empty': "No value selected",
  'decisions.cells.newvalue.date.operator': "Operator",
  'decisions.cells.newvalue.date.start': "Start date",
  'decisions.cells.newvalue.date.end': "End date",
  'decisions.cells.newvalue.date.value': "Date",
  "decisions.cells.newvalue.number.comparisonType": "Comparison",
  "decisions.cells.newvalue.number.comparisonTypeEmpty": "Comparison not selected",
  "decisions.cells.newvalue.number.comparisonValue": "New numerical value",
  "decisions.cells.newvalue.number.comparisonToRange": "Change to range",
  "decisions.cells.newvalue.number.rangeStart": "Start",
  "decisions.cells.newvalue.number.rangeEnd": "End",
  "decisions.cells.newvalue.number.value": "New numerical value",
  "decisions.cells.newvalue.number.rangeIncluded": "Included",
  "decisions.cells.newvalue.number.rangeToComparison": "Change to comparison",
  "decisions.cells.newvalue.string.comparisonType": "Comparison",
  "decisions.cells.newvalue.string.addValue": "Add new value",
  'decisions.cells.newvalue.string.empty': "Comparison not selected",
  'decisions.cells.newvalue.clear': "Clear current value",



  'decisions': "Decisions",
  'services': "Services",
  'program.status.DEPENDENCY_ERROR': "Dependency Errors",
  'program.status.UP': "Program is UP",
  'program.status.AST_ERROR': "Syntax errors",
  'program.status.PROGRAM_ERROR': "Compiler errors",





  'package.explorer.flows': 'flows',
  'package.explorer.servicetasks': 'services',
  'package.explorer.decisiontables': 'decisions',

  'dialog.addtype.title': 'Add new asset',
  'dialog.addtype.button.cancel': 'Cancel',
  'dialog.addtype.button.confirm': 'Create',
  'dialog.addtype.error.unique': 'Asset name must be unique!',
  'dialog.addtype.error.filled': 'Asset name must be filled!',
  'dialog.addtype.input.serviceType': 'Asset type',
  'dialog.addtype.input.name': 'Asset name',

  'dialog.copyas.title': 'Copy asset',
  'dialog.copyas.button.cancel': 'Cancel',
  'dialog.copyas.button.confirm': 'Copy',
  'dialog.copyas.input.from': 'Copy from',
  'dialog.copyas.input.to': 'New asset name',
  'dialog.copyas.error.unique': 'Asset name must be unique!',
  'dialog.copyas.error.filled': 'Asset name must be filled!',

  'dialog.save.title': 'Save asset: {name}',
  'dialog.save.content': "Are you sure you want to save?",
  'dialog.save.errors': "Failed to save asset",
  'dialog.save.button.cancel': 'Cancel',
  'dialog.save.button.confirm': 'Save',

  'dialog.info.title': 'Build info',
  'dialog.info.button.ok': 'OK',

  'error.list.title': 'Failed to complete the operation because of errors:',

  'content.loading': 'loading',

  'releases.table.column.name': 'Name',
  'releases.table.column.message': 'Message',
  'releases.table.column.created': 'Created',
  'releases.table.name': 'All releases',
  'releases.add.error.unique': 'Release must be unique!',
  'releases.add.error.filled': 'Release name must be filled!',
  'releases.add.input.name': 'Name',
  'releases.add.input.msg': 'Comment',
  'releases.add.button.create': 'Create Release',

  'search.input.name': 'Search...',
  'search.groups.found.fl': 'Flows',
  'search.groups.found.ft': 'Flow tasks',
  'search.groups.found.dt': 'Decision tables',
  'search.groups.found.tg': 'Releases',
  'search.header.name': 'Asset name',
  'search.header.created.modified': 'Created/Modified',

  'debug.tab.name': 'Debug asset',

  'toolbar.save': "Save asset",
  'toolbar.copyas': 'copy assets',
  'toolbar.explorer': 'explorer assets',
  'toolbar.reload': 'refresh assets',
  'toolbar.add': 'create new assets',
  'toolbar.debug': 'debug assets',
  'toolbar.releases': 'releases',
  'toolbar.extensions': 'list available extensions',
  'toolbar.info': 'display build info',

  'debug.asset.select.label': "Asset to debug",
  'debug.asset.select.clear': "Clear run data",
  'debug.asset.select.execute': 'Execute asset',
  'debug.asset.execute.inputs': "Debug inputs",

  'debug.asset.execute.outputs.dt.json': "Matched row(s)",
  'debug.asset.execute.outputs.dt.rejects': "Rejected row(s)",
  'debug.asset.execute.outputs.dt.rejects.order': "Execution order",



  'dt.cell.edit.button.cancel': "Cancel",
  'dt.cell.edit.button.confirm': "Apply",

  "dt.toolbar.dt.add.row": "Add new row",
  "dt.toolbar.dt.add.input.column": "Add new input",
  "dt.toolbar.dt.add.output.column": "Add new output",
  "dt.toolbar.dt.hitpolicy.description": "Hit policy",
  "dt.toolbar.csv.download": "Download CSV",
  "dt.toolbar.csv.upload": "Upload CSV",
  "dt.toolbar.dt.organize.rows.columns": "Organize rows/columns",

  "dt.header.edit": "Decision table: {name}, column: {column}",
  "dt.header.edit.title": "Column: {name}",
  "dt.header.delete": "Delete the column",
  "dt.header.script": "Script",
  "dt.header.name": "Name",
  "dt.header.dataType": "Data type",
  "dt.header.direction": "Direction",
  "dt.header.expression": "Expression",

  "dt.menu.created": "Created",
  "dt.menu.modified": "Modified",
  "dt.menu.header": "Decision table: {name}",
  "dt.menu.divider": "Decision table meta",
  "dt.menu.name": "Name",
  "dt.menu.description": "Description",
  "dt.menu.hitpolicy": "Hit policy",

  "dt.edit.row.columns.title": "Modify rows and columns",
  "dt.edit.row.columns.operation": "Select operation",
  "dt.edit.row.columns.operation.delete.column": "Select column to delete",
  "dt.edit.row.columns.operation.delete.row": "Select row to delete",
  "dt.edit.row.columns.operation.delete.row.preview": "Row to delete",

  'dt.cell.newvalue.boolean': "Select boolean value",
  'dt.cell.edit.title': "Decision table: {name}, column: {column}, value: {value}",
  "dt.cell.edit": "Decision table: {name}, column: {column}, value: {value}",
  "dt.cell.comparison": "Comparison",
  "dt.cell.newvalue.add": "Add new value + ENTER",
  "dt.cell.selected": "Selected values",
  "dt.cell.newvalue": "New value",
  "dt.cell.range": "Range",
  "dt.cell.change.comparison": "Change to comparison",
  "dt.cell.change.range": "Change to range",
  "dt.cell.range.include": "Include",
  "dt.cell.range.start": "Start of the range",
  "dt.cell.range.end": "End of the range",
  "dt.cell.date": "Date",
  "dt.cell.boolean": "Boolean",
  "dt.cell.datetime": "Date and time",
  "dt.cell.date.operator": "Operator",
  "dt.cell.novalue.input": "No value entered, so condition is always true",
  "dt.cell.novalue.output": "No value",

};

export default en;
