const en = {
  'buttons.create': "Create",
  'buttons.apply': "Apply",
  'buttons.delete': "Delete",
  'button.cancel': "Cancel",
  'buttons.copy': "Copy",
  'buttons.download': "Download",
  
  'content.loading': 'loading',
  

  'explorer.tabs.flows': 'flows',
  'explorer.tabs.services': 'services',
  'explorer.tabs.decisions': 'decisions',
  'explorer.tabs.search': 'search',

  'activities.title': 'Activities',
  'activities.desc': 'Create, view, and navigate site resources',

  'activities.flows.title': 'Flows',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',

  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',

  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',

  'activities.migration.title': 'Migration',
  'activities.migration.desc': 'Use a JSON file to perform a migration of a site.',

  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.releases.view': 'View all releases',
  'activities.releases.graph': 'Graph',

  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. Not implemented yet!',
  'activities.templates.view': 'View all templates',

  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',  
  'activities.assets.saveSuccess': 'Saved asset: {name}',

  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',


  'programs.error.title': 'Program error',
  'programs.warning.title': 'Program warning',


  'flows': "Flows",
  'options': "Options",

  'migrations.title': "Migration",
  'migrations.create': "Perform migration",
  'migrations.select': "Select tag.json file",

  'flows.edit.title': "Edit flow",
  'flows.copyas.title': "Copy flow as",
  'flows.delete.title': "Delete flow",
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': "Are you sure you want to delete FLOW: {name}?",
  'flows.deleted.message': "Deleted FLOW: {name}",
  'flows.simulate.title': "Debug the flow",

  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',

  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task': "Add existing asset or create new one",
  'flows.autocomplete.task.snackbar.created': "Created new {type}: {name}",
  'flows.autocomplete.task.snackbar.creating': "Creating new {type}: {name}",


  'services.edit.title': "Edit service",
  'services.copyas.title': "Copy service as",
  'services.delete.title': "Delete service",
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': "Are you sure you want to delete SERVICE: {name}?",
  'services.deleted.message': "Deleted SERVICE: {name}",
  'services.simulate.title': "Debug the service",
  
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',


  'decisions.name': "Name",
  'decisions.desc': "Description",
  'decisions.simulate.title': "Debug the decision",
  'decisions.hitpolicy': "Hit-policy",
  'decisions.edit.title': "Edit decision",
  'decisions.copyas.title': "Copy decision as",
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': "Delete decision",
  'decisions.delete.content': "Are you sure you want to delete DECISION: {name}?",
  'decisions.deleted.message': "Deleted DECISION: {name}",
  'decisions.table.hitpolicy': "Matches",
  'decisions.table.options': "Options",

  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',

  'decisions.toolbar.addInputColumn': "Add input column",
  'decisions.toolbar.addOutputColumn': "Add output column",
  'decisions.toolbar.addRow': "Add row",
  'decisions.toolbar.csvDownload': "Download CSV, with separator ';'",
  'decisions.toolbar.csvUpload': "Upload CSV, with separator ';'",
  'decisions.toolbar.nameAndHitpolicy': "Name and hit-policy",
  'decisions.toolbar.organize.rows.columns': "Organize rows and columns",
  'decisions.toolbar.organize.action': "Select action",
  'decisions.toolbar.organize.action.helper': "Move column or row based on name/index",
  'decisions.toolbar.organize.action.expression': "Select expression",
  'decisions.toolbar.organize.action.expression.column': "Select column",
  'decisions.toolbar.organize.action.deleteColumn': "Delete whole column",
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': "Column to move",
  'decisions.toolbar.organize.action.move.from.row': "Row to move",
  'decisions.toolbar.organize.action.move.to.column': "New Position",
  'decisions.toolbar.organize.action.move.to.row': "New Position",

  'decisions.table.inputs.title': "Matching rules",
  'decisions.table.outputs.title': "Results",
  'decisions.header.dialog.title': "Decision table: {name}, column: {column}",
  'decisions.cells.dialog.title': "Decision table: {name}, column: {column}, value: {value}",
  'decisions.cells.newvalue.boolean': "Enter new value",
  'decisions.cells.newvalue.boolean.helper': "Select boolean value",
  'decisions.cells.newvalue.boolean.empty': "No value selected",
  'decisions.cells.newvalue.date.operator': "Operator",
  'decisions.cells.newvalue.date.start': "Start date",
  'decisions.cells.newvalue.date.end': "End date",
  'decisions.cells.newvalue.date.value': "Date",
  "decisions.cells.newvalue.number.comparisonType": "Comparison",
  "decisions.cells.newvalue.number.comparisonTypeEmpty": "Comparison not selected",
  "decisions.cells.newvalue.number.comparisonValue": "New numerical value",
  "decisions.cells.newvalue.number.comparisonToRange": "Change to range",
  "decisions.cells.newvalue.number.rangeStart": "Start",
  "decisions.cells.newvalue.number.rangeEnd": "End",
  "decisions.cells.newvalue.number.value": "New numerical value",
  "decisions.cells.newvalue.number.rangeIncluded": "Included",
  "decisions.cells.newvalue.number.rangeToComparison": "Change to comparison",
  "decisions.cells.newvalue.string.comparisonType": "Comparison",
  "decisions.cells.newvalue.string.addValue": "Add new value",
  "decisions.cells.newvalue.string.available": "Available values",
  "decisions.cells.newvalue.string.selected": "Selected values",
  'decisions.cells.newvalue.string.empty': "Comparison not selected",
  'decisions.cells.newvalue.clear': "Clear current value",

  'decisions.valueSet': "Define value set",
  'decisions.valueSet.description': "Value sets can be used to define a predetermined set of values for any input",
  'decisions.valueSet.add': "Add to value set",
  'decisions.valueSet.remove': "Remove from value set",
  'decisions.valueSet.current': "Current value set",
  'decisions.valueSet.empty': "Value set is empty",

  'dt.header.name': "Name",
  'dt.header.delete': "Delete",
  'dt.header.expression': "Expression",
  'dt.header.dataType': "Data type",
  'dt.header.script': "Script",

  'decisions': "Decisions",
  'services': "Services",
  'program.status.DEPENDENCY_ERROR': "Dependency Errors",
  'program.status.UP': "Program is UP",
  'program.status.AST_ERROR': "Syntax errors",
  'program.status.PROGRAM_ERROR': "Compiler errors",





  'package.explorer.flows': 'flows',
  'package.explorer.servicetasks': 'services',
  'package.explorer.decisiontables': 'decisions',

  'dialog.addtype.title': 'Add new asset',
  'dialog.addtype.button.cancel': 'Cancel',
  'dialog.addtype.button.confirm': 'Create',
  'dialog.addtype.error.unique': 'Asset name must be unique!',
  'dialog.addtype.error.filled': 'Asset name must be filled!',
  'dialog.addtype.input.serviceType': 'Asset type',
  'dialog.addtype.input.name': 'Asset name',

  'dialog.copyas.title': 'Copy asset',
  'dialog.copyas.button.cancel': 'Cancel',
  'dialog.copyas.button.confirm': 'Copy',
  'dialog.copyas.input.from': 'Copy from',
  'dialog.copyas.input.to': 'New asset name',
  'dialog.copyas.error.unique': 'Asset name must be unique!',
  'dialog.copyas.error.filled': 'Asset name must be filled!',

  'dialog.save.title': 'Save asset: {name}',
  'dialog.save.content': "Are you sure you want to save?",
  'dialog.save.errors': "Failed to save asset",
  'dialog.save.button.cancel': 'Cancel',
  'dialog.save.button.confirm': 'Save',

  'releases.delete.content': 'Are you sure you want to delete release: {name}',
  'releases.composer.createdMessage': 'Created new release {name}',
  'release.delete.title': 'Delete release',
  'release.deleted.message': 'Release {name} deleted',
  'releases.view.note': 'Release notes',
  'releases.view.tag': 'Release version name',
  'releases.view.created': 'Date and time',
  'releases.view.download': 'JSON download',
  'releases.composer.title': "Create new release",
  'releases.composer.assetName': "Release name",
  'releases.composer.assetDesc': "Release description",
  'releases.composer.errorsTitle': "Error while creating release",
  'releases.table.column.name': 'Name',
  'releases.table.column.message': 'Message',
  'releases.table.column.created': 'Created',
  'releases.table.name': 'All releases',
  'releases.add.error.unique': 'Release must be unique!',
  'releases.add.error.filled': 'Release name must be filled!',
  'releases.add.input.name': 'Name',
  'releases.add.input.msg': 'Comment',
  'releases.add.button.create': 'Create Release',


  'debug.toolbar.options': "Options",
  'debug.toolbar.selectAsset': "Select asset to debug",
  'debug.toolbar.inputCsv': "Define input data as a CSV",
  'debug.toolbar.inputForm': "Define input data as a FORM",
  'debug.toolbar.inputJson': "Define input data as a JSON",
  'debug.toolbar.execute': "Execute",
  'debug.toolbar.noAsset': "Select asset from options",
  'debug.toolbar.openAsset': "Open",
  'debug.toolbar.download': "Download results as CSV",
    
  'debug.input.noAsset': "There is no ASSET selected",
  'debug.input.form': "Debug using FORM",
  'debug.input.formTitle': "Define inputs",
  'debug.input.form.invalid.integer': "Value must be an integer",
  'debug.input.form.invalid.number': "Value must be a number",
  'debug.input.form.invalid.range': "Value must be in the specified range",
  'debug.input.json': "Debug using JSON",
  'debug.input.jsonTitle': "Define JSON input",
  'debug.input.csvUpload': "Debug using CSV",
  'debug.input.csvFile': "Upload CSV FILE",
  'debug.input.csvFileTitle': "Upload CSV file - semicolon-delimited (;)",
  'debug.input.csvFileOrText': "Or paste CSV contents - semicolon-delimited (;)",
  'debug.inputs.fieldName': "Field Name",
  'debug.inputs.fieldValue': "Field Value",
  
  'debug.select.title': "Select asset to debug",
  'debug.select.assetType': "Asset type to filter",
  'debug.select.searchField': "Asset name to search",
  'debug.select.searchHelper': "Search matches asset name or description",
  'debug.select.searchPlaceholder': "Keyword to search",
  'debug.select.searchResults': "Found assets",
  'debug.select.confirm': "Select",
  
  'debug.inputs.format': "Asset input format: {type}",
  

  'debug.asset.select.label': "Asset to debug",
  'debug.asset.select.clear': "Clear run data",
  'debug.asset.select.execute': 'Execute asset',
  'debug.asset.execute.inputs': "Debug inputs",
  'debug.asset.execute.errors': "Execution errors",

  'debug.asset.execute.outputs.dt.json': "Matched row(s)",
  'debug.asset.execute.outputs.dt.rejects': "Rejected row(s)",
  'debug.asset.execute.outputs.dt.rejects.order': "Execution order",

  'debug.asset.execute.outputs.flow.step': "Step name: {name}, status: {status}",

  'debug.csv.row': "Data row: {row}",
  'debug.csv.download': "Download results as CSV",
  'debug.csv.download.delimiter': "Choose a delimiter for the CSV file",
  'debug.csv.download.delimiter.semicolon': "Semicolon (;)",
  'debug.csv.download.delimiter.comma': "Comma (,)",
  'debug.csv.download.options': "Export options",
  'debug.csv.download.wrap': "Wrap cells containing delimiters with quotes",


};

export default en;
